const realms = {
  khadgar: 'Khadgar',
  chromaggus: 'Chromaggus',
  dentarg: 'Dentarg',
  'la-croisade-écarlate': 'La Croisade écarlate',
  runetotem: 'Runetotem',
  shadowsong: 'Shadowsong',
  silvermoon: 'Silvermoon',
  sunstrider: 'Sunstrider',
  executus: 'Executus',
  mazrigos: 'Mazrigos',
  karazhan: 'Karazhan',
  auchindoun: 'Auchindoun',
  'shattered-halls': 'Shattered Halls',
  gordunni: 'Gordunni',
  soulflayer: 'Soulflayer',
  deathguard: 'Deathguard',
  sporeggar: 'Sporeggar',
  nethersturm: 'Nethersturm',
  shattrath: 'Shattrath',
  deepholm: 'Deepholm',
  echsenkessel: 'Echsenkessel',
  blutkessel: 'Blutkessel',
  galakrond: 'Galakrond',
  razuvious: 'Razuvious',
  deathweaver: 'Deathweaver',
  terenas: 'Terenas',
  thunderhorn: 'Thunderhorn',
  turalyon: 'Turalyon',
  ravencrest: 'Ravencrest',
  'shattered-hand': 'Shattered Hand',
  spinebreaker: 'Spinebreaker',
  stormscale: 'Stormscale',
  'earthen-ring': 'Earthen Ring',
  alexstrasza: 'Alexstrasza',
  alleria: 'Alleria',
  antonidas: 'Antonidas',
  blackhand: 'Blackhand',
  gilneas: 'Gilneas',
  kargath: 'Kargath',
  khazgoroth: "Khaz'goroth",
  madmortem: 'Madmortem',
  zuluhed: 'Zuluhed',
  nozdormu: 'Nozdormu',
  perenolde: 'Perenolde',
  aegwynn: 'Aegwynn',
  'dun-morogh': 'Dun Morogh',
  thrall: 'Thrall',
  theradras: 'Theradras',
  genjuros: 'Genjuros',
  balnazzar: 'Balnazzar',
  wrathbringer: 'Wrathbringer',
  talnivarr: 'Talnivarr',
  emeriss: 'Emeriss',
  drakthul: "Drak'thul",
  ahnqiraj: "Ahn'Qiraj",
  ysera: 'Ysera',
  malygos: 'Malygos',
  anetheron: 'Anetheron',
  nazjatar: 'Nazjatar',
  tichondrius: 'Tichondrius',
  'steamwheedle-cartel': 'Steamwheedle Cartel',
  'die-ewige-wacht': 'Die ewige Wacht',
  'die-todeskrallen': 'Die Todeskrallen',
  'die-arguswacht': 'Die Arguswacht',
  uldaman: 'Uldaman',
  'confrérie-du-thorium': 'Confrérie du Thorium',
  dragonblight: 'Dragonblight',
  'tarren-mill': 'Tarren Mill',
  cthun: "C'Thun",
  alonsus: 'Alonsus',
  'blades-edge': "Blade's Edge",
  doomhammer: 'Doomhammer',
  'twilights-hammer': "Twilight's Hammer",
  daggerspine: 'Daggerspine',
  sargeras: 'Sargeras',
  'emerald-dream': 'Emerald Dream',
  quelthalas: "Quel'Thalas",
  bloodscalp: 'Bloodscalp',
  'burning-blade': 'Burning Blade',
  crushridge: 'Crushridge',
  dragonmaw: 'Dragonmaw',
  dunemaul: 'Dunemaul',
  dethecus: 'Dethecus',
  durotan: 'Durotan',
  aggramar: 'Aggramar',
  arathor: 'Arathor',
  azjolnerub: 'Azjol-Nerub',
  draenor: 'Draenor',
  voljin: "Vol'jin",
  arakarahm: 'Arak-arahm',
  zenedar: 'Zenedar',
  agamaggan: 'Agamaggan',
  bladefist: 'Bladefist',
  'culte-de-la-rive-noire': 'Culte de la Rive noire',
  'argent-dawn': 'Argent Dawn',
  onyxia: 'Onyxia',
  nefarian: 'Nefarian',
  'das-syndikat': 'Das Syndikat',
  'laughing-skull': 'Laughing Skull',
  neptulon: 'Neptulon',
  'twisting-nether': 'Twisting Nether',
  'the-maelstrom': 'The Maelstrom',
  bloodfeather: 'Bloodfeather',
  frostwhisper: 'Frostwhisper',
  korgall: "Kor'gall",
  'defias-brotherhood': 'Defias Brotherhood',
  rashgarroth: 'Rashgarroth',
  'les-sentinelles': 'Les Sentinelles',
  suramar: 'Suramar',
  garrosh: 'Garrosh',
  arygos: 'Arygos',
  teldrassil: 'Teldrassil',
  lordaeron: 'Lordaeron',
  'aggra-português': 'Aggra (Português)',
  terokkar: 'Terokkar',
  baelgun: 'Baelgun',
  chogall: "Cho'gall",
  nordrassil: 'Nordrassil',
  sylvanas: 'Sylvanas',
  drekthar: "Drek'Thar",
  ghostlands: 'Ghostlands',
  'the-shatar': "The Sha'tar",
  'chants-éternels': 'Chants éternels',
  'marécage-de-zangar': 'Marécage de Zangar',
  naxxramas: 'Naxxramas',
  arthas: 'Arthas',
  azshara: 'Azshara',
  blackmoore: 'Blackmoore',
  destromath: 'Destromath',
  eredar: 'Eredar',
  frostwolf: 'Frostwolf',
  kiljaeden: "Kil'jaeden",
  malganis: "Mal'Ganis",
  'zirkel-des-cenarius': 'Zirkel des Cenarius',
  vashj: 'Vashj',
  hyjal: 'Hyjal',
  ulduar: 'Ulduar',
  'howling-fjord': 'Howling Fjord',
  alakir: "Al'Akir",
  stormreaver: 'Stormreaver',
  magtheridon: 'Magtheridon',
  'lightnings-blade': "Lightning's Blade",
  'kirin-tor': 'Kirin Tor',
  archimonde: 'Archimonde',
  elune: 'Elune',
  'chamber-of-aspects': 'Chamber of Aspects',
  ravenholdt: 'Ravenholdt',
  'pozzo-delleternità': "Pozzo dell'Eternità",
  eonar: 'Eonar',
  veknilash: "Vek'nilash",
  frostmane: 'Frostmane',
  bloodhoof: 'Bloodhoof',
  kaelthas: "Kael'thas",
  haomarush: 'Haomarush',
  'khaz-modan': 'Khaz Modan',
  varimathras: 'Varimathras',
  hakkar: 'Hakkar',
  blackrock: 'Blackrock',
  kelthuzad: "Kel'Thuzad",
  mannoroth: 'Mannoroth',
  proudmoore: 'Proudmoore',
  garona: 'Garona',
  'darkmoon-faire': 'Darkmoon Faire',
  veklor: "Vek'lor",
  mugthol: "Mug'thol",
  taerar: 'Taerar',
  dalvengyr: 'Dalvengyr',
  rajaxx: 'Rajaxx',
  malorne: 'Malorne',
  'der-abyssische-rat': 'Der abyssische Rat',
  'der-mithrilorden': 'Der Mithrilorden',
  ambossar: 'Ambossar',
  krasus: 'Krasus',
  arathi: 'Arathi',
  ysondre: 'Ysondre',
  eldrethalas: "Eldre'Thalas",
  kilrogg: 'Kilrogg',
  wildhammer: 'Wildhammer',
  saurfang: 'Saurfang',
  nemesis: 'Nemesis',
  fordragon: 'Fordragon',
  'borean-tundra': 'Borean Tundra',
  'les-clairvoyants': 'Les Clairvoyants',
  skullcrusher: 'Skullcrusher',
  lothar: 'Lothar',
  sinstralis: 'Sinstralis',
  terrordar: 'Terrordar',
  'scarshield-legion': 'Scarshield Legion',
  'kul-tiras': 'Kul Tiras',
  stormrage: 'Stormrage',
  nerzhul: "Ner'zhul",
  'dun-modr': 'Dun Modr',
  zuljin: "Zul'jin",
  uldum: 'Uldum',
  sanguino: 'Sanguino',
  shendralar: "Shen'dralar",
  tyrande: 'Tyrande',
  exodar: 'Exodar',
  'los-errantes': 'Los Errantes',
  lightbringer: 'Lightbringer',
  darkspear: 'Darkspear',
  'burning-steppes': 'Burning Steppes',
  'bronze-dragonflight': 'Bronze Dragonflight',
  anachronos: 'Anachronos',
  'colinas-pardas': 'Colinas Pardas',
  ungoro: "Un'Goro",
  illidan: 'Illidan',
  rexxar: 'Rexxar',
  'festung-der-stürme': 'Festung der Stürme',
  guldan: "Gul'dan",
  aszune: 'Aszune',
  'aerie-peak': 'Aerie Peak',
  xavius: 'Xavius',
  throkferoth: "Throk'Feroth",
  minahonda: 'Minahonda',
  tirion: 'Tirion',
  senjin: "Sen'jin",
  trollbane: 'Trollbane',
  amanthul: "Aman'Thul",
  bronzebeard: 'Bronzebeard',
  'die-aldor': 'Die Aldor',
  'temple-noir': 'Temple noir',
  eversong: 'Eversong',
  thermaplugg: 'Thermaplugg',
  grom: 'Grom',
  goldrinn: 'Goldrinn',
  blackscar: 'Blackscar',
  forscherliga: 'Forscherliga',
  eitrigg: 'Eitrigg',
  todeswache: 'Todeswache',
  dalaran: 'Dalaran',
  frostmourne: 'Frostmourne',
  malfurion: 'Malfurion',
  kragjin: "Krag'jin",
  gorgonnash: 'Gorgonnash',
  'burning-legion': 'Burning Legion',
  azuremyst: 'Azuremyst',
  anubarak: "Anub'arak",
  nerathor: "Nera'thor",
  'kult-der-verdammten': 'Kult der Verdammten',
  'der-rat-von-dalaran': 'Der Rat von Dalaran',
  hellscream: 'Hellscream',
  ragnaros: 'Ragnaros',
  darksorrow: 'Darksorrow',
  'the-venture-co': 'The Venture Co',
  'grim-batol': 'Grim Batol',
  jaedenar: 'Jaedenar',
  kazzak: 'Kazzak',
  moonglade: 'Moonglade',
  'conseil-des-ombres': 'Conseil des Ombres',
  nathrezim: 'Nathrezim',
  'das-konsortium': 'Das Konsortium',
  boulderfist: 'Boulderfist',
  deathwing: 'Deathwing',
  'area-52': 'Area 52',
  'die-nachtwache': 'Die Nachtwache',
  'booty-bay': 'Booty Bay',
  'lich-king': 'Lich King',
  hellfire: 'Hellfire',
  outland: 'Outland',
  greymane: 'Greymane',
  medivh: 'Medivh',
  'die-silberne-hand': 'Die Silberne Hand',
  nagrand: 'Nagrand',
  azuregos: 'Azuregos',
  ashenvale: 'Ashenvale',
  norgannon: 'Norgannon',
} as Record<string, string>

export type RealmValue = typeof realms[keyof typeof realms]
export type RealmKey = keyof typeof realms

const shortNames = Object.keys(realms)
const fullNames = Object.values(realms)
export { realms, shortNames, fullNames }
